### ISSUE TITLE
1.0rc checklist

### ISSUE THREAD

**Issue by stephenmoloney** [stephenmoloney/fastimage#12]
- [x] returned errors, some degree of tidy up needed here for errors bubbling up from private functions
- [x] make multiple versions of :hackney acceptable
- [x] support binaries in addition to a file path or uri
- [x] change return image type return types to atoms `@type image_types :: :bmp | :gif | :jpg | :png`
- [x] change errors to Elixir Exceptions - eg `UnknownTypeError`
- [x] introduce type -> {:ok, type} and size -> {:ok, size}, type!, and size! function formats [will need to change raise(inspect(error)) -> raise(error) ]
- [x] credo linting
- [x] ensure close_stream in all relevant locations
- [x] added new `Fastimage.info` function
- [x] add options to `type/1`, `size/1` and `info/1` to allow manual overrides on 
the otherwised fixed values for `stream_timeout`, `max_redirect_retries` and 
`max_error_retries`

**Comment by stephenmoloney** [comment]
merged
